version: "3"

services:
  app:
    image: simplycodedsoftware/ci:7.4
    volumes:
      - "$PWD:/data/app"
    user: 1000:1000
    working_dir: "/data/app"
    command: sleep 99999
    networks:
      - default